### ISSUE TITLE
successful matches and future match eligibility

### ISSUE THREAD

**Issue by margocramer** [open-path/Boston#32]
submitted by Allison.

There is a current workaround for impacted clients. Will score in July when Ian is back. 

Clients with provider route can only get 1 match for provider route ever. From Elliot: "Once successful a client won’t re-match a vacancy on the same route." 

Small scale, this is affecting clients with successful RRH matches who are being submitted for BHA HCVs. Larger issue longer term -- Ian G and I want to dicsuss -- does this mean someone who gets a RRH CAS Match can never get a second one? For example if someone got a CAS match to RRH in 2019, exited, returned to homelessness in 2023 and was eligible for RRH again -- they wouldn't ever get that match? 

It sounds like this is how the system is working right now. Do we want it to work that way?

**Comment by margocramer** [comment]
7/9/19: 
Ian to raise these questions with Laila/Policy in coming weeks for more feedback.

currently - 2 people have to go outside of CAS for housing opportunity they are eligible for. This will be EVERYONE who is ever successfully matched to RRH?

How do we trigger someone getting "back" into the queue?
This came up for Housing Choice Vouchers, and we recognize this will continue to come up.

Conversation for Wednesday with Green River?
What are the rules around matching for CoC RRH? We should check in with Sean.
Does this also apply to default match route (ie PSH) - enrolled, then drop out and come back?

Workaround is happening (Ian emails to Nancy...)

This feels like a "policy group" discussion to identify specific policies around each resource.

**Comment by eanders** [comment]
One possible technical solution:

What if we only blocked you from matching for 90 days after a successful match.  That would give 90 days to update HMIS data such that a client would no longer be eligible (exited from homeless programs or enrolled in PH, tags removed, etc.)  If someone became eligible, or was still eligible 90 days after a successful match, they could go back into the match pool.

**Comment by lmckone** [comment]
Notes from 7/17:

Feedback:
From RRH WG - in order to match to RRH again, client would need exit from RRH program (pre-placement and/or stabilization) in HMIS, and then a re-assessment
From Policy Group -
Cost-benefit analysis - is this worth figuring out a long-term solution for, or is this a small scale issue that can rely on a manual workaround?
Is this an issue specific to HCVs?
No, its relevant to HSA and RRH once it expands, and will impact PSH matches as well
Could we create sub	types for the Provider Only Route so that parking in an HCV or RRH route does not impact the other?
Current state: 
2 routes, Provider Only (RRH and HCV) and Default Route (PSH)
One and only one match per route
2 issues
We want people that get RRH in Provider Only Route to be able to match to HCVs or other types of vouchers within Provider Only Route
We want multiple matches per route if someone “flames out” of a prior successful match in that route
Need to establish criteria for re-matching across all types of programs
Other things to consider
Communications flow (e-mail notifications) is route-specific 
What else would this be relevant in the next 12 months
If we got a bunch of MRVP vouchers
How would this work for Non-HMIS clients in RRH?
They won’t have exit dates if they’re enrolled in a non-HMIS Rapid program
Maybe: ineligible until assessed again (would have to run by policy group)
Next Steps
DND group will sketch out internally
GR will give rough estimates of the options discussed today

**Comment by margocramer** [comment]
Technology Group move this to Implementation group - as a priority item.

**Comment by margocramer** [comment]
still waiting for implementation group to address

**Comment by margocramer** [comment]
see tech group notes 7/31/19
