### ISSUE TITLE
Make open-path/Boston repo private

### ISSUE THREAD

**Issue by lmckone** [open-path/Boston#74]
Could we make this repo private since we're now tracking bugs here? I thought it was already private, but only the Development Tracker Project is. Thanks!

**Comment by iankozak** [comment]
We're trying. We upgraded the organization's account to "Pro," which should allow making the repo private, but we still don't have that option. We opened a support ticket with Git 3/10.

**Comment by lmckone** [comment]
Gotcha! Thanks for the update.

**Comment by lmckone** [comment]
Could you also add @kadraadderly to the organization? Also, I think it makes sense for us at DND to own this repo/organization since it's just for project management. We'd also be able to incur any costs associated with Github Pro. That way we can modify configurations/add people easily without bugging you guys. We can go over details on Monday but just wanted to mention it.

**Comment by iankozak** [comment]
Check, Kadra should be added.

Turns out an organization account can't have a private repo without upgrading to 'Team' for ~$1200/year.

However, a 'Pro' personal account ($84/year) can have a private repo, so we were going to suggest we set-up a personal account and move the repo under that. If you guys want to do that instead, however, we're good with that.

**Comment by lmckone** [comment]
Thanks for researching this! Heads up @SusannaRH22

**Comment by lmckone** [comment]
DND team looking into acquiring Github Team
